# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MMD' do
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'HYBNetworking'
    pod 'RealReachability'
end

target 'MMDTests' do

end

target 'MMDUITests' do

end

