# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MMD' do
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'RealReachability'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'YYKeyboardManager'
    pod 'YYKit'
end

target 'MMDTests' do

end

target 'MMDUITests' do

end

