# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MMD' do
    pod 'AFNetworking'
    pod 'SVProgressHUD'
    pod 'RealReachability'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'YYKit'
    pod 'SDAutoLayout'
    
    pod 'ShareSDK3'
    pod 'MOBFoundation_IDFA'
    pod 'ShareSDK3/ShareSDKUI'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ShareSDK3/ShareSDKPlatforms/Messenger'
end

target 'MMDTests' do

end

target 'MMDUITests' do

end

